Set-Item env:MCP_MODE "stdio"
Set-Item env:LOG_LEVEL "error"
Set-Item env:DISABLE_CONSOLE_OUTPUT "true"
Set-Item env:N8N_API_URL "http://localhost:5678"
Set-Item env:N8N_API_KEY "<eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZTk5ZTU2OS00OTg3LTQwODYtOTJiNy1hMDBlN2FlMDgwODUiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzY1MDI5NDI0LCJleHAiOjE3NzI3MjY0MDB9.b89jQXW0oTu5PkAUoiR8qxcaXMiJsAaPxZXHevRLN1M>"
npx n8n-mcp